export function agenteIaView() {
  return `
    <div class="app-shell">
      <aside class="drawer" id="drawer" aria-label="Navegação principal">
        <div class="drawer__top"><a class="brand" href="#inicio" aria-label="AtendeAI início"><img class="brand__logo" src="assets/logo-atendeai.svg" alt="AtendeAI" /></a><button class="icon-button drawer__close" id="close-drawer" type="button" aria-label="Fechar menu"><i data-lucide="x"></i></button></div>
        <nav class="nav-list"><p class="nav-list__label">Visão geral</p><a class="nav-item" href="#inicio"><i data-lucide="layout-dashboard"></i><span>Dashboard</span></a><a class="nav-item" href="#pedidos"><i data-lucide="shopping-bag"></i><span>Pedidos</span><b>12</b></a><a class="nav-item" href="#reservas"><i data-lucide="calendar-days"></i><span>Reservas</span></a><p class="nav-list__label nav-list__label--spaced">Operação</p><a class="nav-item" href="#cardapio"><i data-lucide="utensils"></i><span>Cardápio</span></a><a class="nav-item is-active" href="#agente-ia"><i data-lucide="bot"></i><span>Agente de IA</span></a><a class="nav-item" href="#relatorios"><i data-lucide="chart-no-axes-combined"></i><span>Relatórios</span></a></nav>
        <div class="drawer__bottom"><a class="nav-item" href="#configuracoes"><i data-lucide="settings-2"></i><span>Configurações</span></a><div class="help-card"><span class="help-card__icon"><i data-lucide="message-circle"></i></span><strong>Precisa de ajuda?</strong><small>Fale com nosso suporte</small><i class="help-card__arrow" data-lucide="arrow-up-right"></i></div><div class="profile"><span class="avatar avatar--orange">JS</span><span><strong>João Silva</strong><small>Administrador</small></span><i data-lucide="more-horizontal"></i></div></div>
      </aside>
      <div class="drawer-overlay" id="drawer-overlay"></div>
      <main class="main-content" id="agente-ia">
        <header class="topbar"><button class="icon-button menu-trigger" id="open-drawer" type="button" aria-label="Abrir menu" aria-controls="drawer" aria-expanded="false"><i data-lucide="menu"></i></button><div class="breadcrumb"><span>Operação</span><i data-lucide="chevron-right"></i><strong>Agente de IA</strong></div><div class="topbar__actions"><span class="agent-status"><i></i> Central operacional</span><button class="icon-button notification" type="button" aria-label="Notificações"><i data-lucide="bell"></i><span></span></button></div></header>
        <section class="content-wrap agent-page">
          <div class="agent-intro"><div><p class="eyebrow">Atendimento automatizado</p><h1>Agente de IA</h1><p class="subtitle">Conecte o WhatsApp e configure o atendente virtual do Manjericão.</p></div><span class="agent-intro__badge"><i data-lucide="zap"></i> Evolution API</span></div>
          <section class="connection-card" id="whatsapp-connection"><div class="connection-card__icon"><i data-lucide="message-circle"></i></div><div class="connection-card__copy"><span class="connection-card__eyebrow">WhatsApp do restaurante</span><h2 id="connection-title">WhatsApp não conectado</h2><p id="connection-description">Conecte uma linha para o atendente começar a conversar com seus clientes.</p></div><div class="connection-card__action"><span class="connection-status is-disconnected" id="connection-status"><i></i> Desconectado</span><button class="connect-button" id="connect-whatsapp" type="button"><i data-lucide="qr-code"></i> Conectar WhatsApp</button><button class="disconnect-button" id="disconnect-whatsapp" type="button" hidden><i data-lucide="unlink"></i> Desconectar</button></div></section>
          <section class="qr-panel panel" id="qr-panel" hidden><div><span class="eyebrow">Pareamento seguro</span><h2>Escaneie o QR Code pelo WhatsApp</h2><p>Abra o WhatsApp no celular, acesse Dispositivos conectados e escaneie este código.</p><button class="demo-connect" id="demo-connect" type="button">Simular conexão concluída</button></div><div class="qr-frame"><img id="whatsapp-qr" alt="QR Code para conectar o WhatsApp" /><small>O código expira em 60 segundos</small></div></section>
          <section class="agent-settings-grid"><section class="panel agent-settings-card"><div class="settings-section__header"><div><span class="eyebrow">Personalidade do robô</span><h2>Como o agente deve atender</h2><p>Defina o tom e as regras que ele seguirá no WhatsApp.</p></div><span class="agent-settings-icon"><i data-lucide="bot"></i></span></div><form class="agent-form" id="agent-config-form"><label>Nome do assistente<input id="assistant-name" type="text" value="Atendente do Manjericão" /></label><label>Instruções do sistema<textarea id="assistant-prompt" rows="6">Você é o atendente virtual do Manjericão. Seja simpático, objetivo e nunca invente informações. Informe horários, taxa de delivery, formas de pagamento e encaminhe casos fora do seu alcance para a equipe.</textarea></label><div class="agent-form__footer"><small id="agent-save-status">Alterações salvas localmente</small><button class="settings-save" type="submit">Salvar configurações</button></div></form></section><aside class="agent-control-column"><section class="panel automation-card"><div class="automation-card__top"><div><span class="eyebrow">Controle mestre</span><h2>Atendimento automático</h2></div><label class="master-toggle"><input id="automation-toggle" type="checkbox" checked /><i></i></label></div><p id="automation-description">O agente pode responder clientes automaticamente pelo WhatsApp conectado.</p><span class="automation-state" id="automation-state"><i></i> Ativo e pronto para atender</span></section><section class="panel agent-status-card"><div class="agent-status-card__icon"><i data-lucide="shield-check"></i></div><h2>Regras de segurança</h2><ul><li>Não confirma pedidos sem disponibilidade.</li><li>Encaminha reclamações para a equipe.</li><li>Respeita seus horários de funcionamento.</li></ul></section></aside></section>
        </section>
      </main>
    </div>`;
}
