export function dashboardView() {
  return `
    <div class="app-shell">
      <aside class="drawer" id="drawer" aria-label="Navegação principal">
        <div class="drawer__top"><a class="brand" href="#inicio" aria-label="AtendeAI início"><img class="brand__logo" src="assets/logo-atendeai.svg" alt="AtendeAI" /></a><button class="icon-button drawer__close" id="close-drawer" type="button" aria-label="Fechar menu"><i data-lucide="x"></i></button></div>
        <nav class="nav-list"><p class="nav-list__label">Visão geral</p><a class="nav-item is-active" href="#inicio"><i data-lucide="layout-dashboard"></i><span>Dashboard</span></a><a class="nav-item" href="#pedidos"><i data-lucide="shopping-bag"></i><span>Pedidos</span><b>12</b></a><a class="nav-item" href="#reservas"><i data-lucide="calendar-days"></i><span>Reservas</span></a><p class="nav-list__label nav-list__label--spaced">Operação</p><a class="nav-item" href="#cardapio"><i data-lucide="utensils"></i><span>Cardápio</span></a><a class="nav-item" href="#clientes"><i data-lucide="users"></i><span>Clientes</span></a><a class="nav-item" href="#relatorios"><i data-lucide="chart-no-axes-combined"></i><span>Relatórios</span></a></nav>
        <div class="drawer__bottom"><a class="nav-item" href="#configuracoes"><i data-lucide="settings-2"></i><span>Configurações</span></a><div class="help-card"><span class="help-card__icon"><i data-lucide="message-circle"></i></span><strong>Precisa de ajuda?</strong><small>Fale com nosso suporte</small><i class="help-card__arrow" data-lucide="arrow-up-right"></i></div><div class="profile"><span class="avatar avatar--orange">JS</span><span><strong>João Silva</strong><small>Administrador</small></span><i data-lucide="more-horizontal"></i></div></div>
      </aside>
      <div class="drawer-overlay" id="drawer-overlay"></div>
      <main class="main-content" id="inicio">
        <header class="topbar"><button class="icon-button menu-trigger" id="open-drawer" type="button" aria-label="Abrir menu" aria-controls="drawer" aria-expanded="false"><i data-lucide="menu"></i></button><div class="breadcrumb"><span>Visão geral</span><i data-lucide="chevron-right"></i><strong>Dashboard</strong></div><div class="topbar__actions"><button class="date-picker" type="button"><i data-lucide="calendar"></i> 01 - 07 Jun, 2024 <i data-lucide="chevron-down"></i></button><button class="icon-button notification" type="button" aria-label="Notificações"><i data-lucide="bell"></i><span></span></button></div></header>
        <section class="content-wrap">
          <div class="welcome-row"><div><p class="eyebrow">Sábado, 07 de junho de 2024</p><h1>Bom dia, João <span>✦</span></h1><p class="subtitle">O movimento está bom. Veja os números da sua operação hoje.</p></div></div>
          <div class="metric-grid"><article class="metric-card metric-card--accent"><div class="metric-card__heading"><span>Receita da semana</span><i data-lucide="more-horizontal"></i></div><strong>R$ 12.840,00</strong><p class="trend trend--up"><i data-lucide="trending-up"></i> 18,4% <span>vs. semana passada</span></p><div class="metric-card__footer"><span class="metric-dot metric-dot--orange"></span> 284 pedidos</div></article><article class="metric-card"><div class="metric-card__heading"><span>Pedidos hoje</span><i data-lucide="more-horizontal"></i></div><strong>48</strong><p class="trend trend--up"><i data-lucide="trending-up"></i> 12,6% <span>vs. ontem</span></p><div class="metric-card__footer"><span class="metric-dot metric-dot--green"></span> 12 em andamento</div></article><article class="metric-card"><div class="metric-card__heading"><span>Ticket médio</span><i data-lucide="more-horizontal"></i></div><strong>R$ 45,21</strong><p class="trend trend--down"><i data-lucide="trending-down"></i> 3,2% <span>vs. semana passada</span></p><div class="metric-card__footer"><span class="metric-dot metric-dot--blue"></span> Meta: R$ 50,00</div></article></div>
          <div class="dashboard-grid"><section class="panel sales-panel"><div class="panel__header"><div><h2>Receita ao longo da semana</h2><p>Uma visão rápida do ritmo da casa</p></div><button class="select-button" type="button">Esta semana <i data-lucide="chevron-down"></i></button></div><div class="chart"><div class="chart__labels"><span>R$ 4k</span><span>R$ 3k</span><span>R$ 2k</span><span>R$ 1k</span><span>R$ 0</span></div><div class="chart__area"><div class="grid-lines"><i></i><i></i><i></i><i></i><i></i></div><svg viewBox="0 0 600 180" preserveAspectRatio="none" aria-label="Gráfico de receita"><defs><linearGradient id="area-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#e6a35b" stop-opacity=".3"/><stop offset="100%" stop-color="#e6a35b" stop-opacity="0"/></linearGradient></defs><path class="chart-fill" d="M0,145 C35,130 45,138 72,116 S115,125 145,100 S183,86 214,108 S252,92 280,72 S323,90 350,62 S390,78 420,52 S462,61 490,42 S535,66 560,26 S590,43 600,18 L600,180 L0,180Z"/><path class="chart-line" d="M0,145 C35,130 45,138 72,116 S115,125 145,100 S183,86 214,108 S252,92 280,72 S323,90 350,62 S390,78 420,52 S462,61 490,42 S535,66 560,26 S590,43 600,18"/></svg><div class="chart__days"><span>Dom</span><span>Seg</span><span>Ter</span><span>Qua</span><span>Qui</span><span>Sex</span><span>Sáb</span></div></div></div></section><section class="panel operations-panel"><div class="panel__header"><div><h2>Operação hoje</h2><p>O pulso do restaurante agora</p></div><span class="live-indicator"><i></i> Ao vivo</span></div><div class="circle-grid"><div class="circle-stat"><div class="donut donut--orange"><span>78<small>%</small></span></div><strong>Ocupação</strong><small>39 de 50 lugares</small></div><div class="circle-stat"><div class="donut donut--green"><span>62<small>%</small></span></div><strong>Delivery</strong><small>29 pedidos hoje</small></div></div><div class="channel-row"><span><i class="channel-dot channel-dot--orange"></i> Salão <b>55%</b></span><span><i class="channel-dot channel-dot--green"></i> Delivery <b>32%</b></span><span><i class="channel-dot channel-dot--blue"></i> Retirada <b>13%</b></span></div></section></div>
          <section class="panel orders-panel orders-panel--wide"><div class="panel__header"><div><h2>Pedidos recentes</h2><p>Acompanhe a operação sem perder o ritmo</p></div><a class="text-link" href="#pedidos">Ver todos <i data-lucide="arrow-up-right"></i></a></div><div class="order-list order-list--wide"><div class="order-row"><span class="order-icon order-icon--orange"><i data-lucide="shopping-bag"></i></span><span><strong>#1048 · Mesa 06</strong><small>2 itens · 12:42</small></span><b>R$ 128,00</b><em class="status status--preparing">Preparando</em></div><div class="order-row"><span class="order-icon order-icon--green"><i data-lucide="shopping-bag"></i></span><span><strong>#1047 · Delivery</strong><small>4 itens · 12:35</small></span><b>R$ 86,50</b><em class="status status--ready">Pronto</em></div><div class="order-row"><span class="order-icon order-icon--blue"><i data-lucide="shopping-bag"></i></span><span><strong>#1046 · Mesa 12</strong><small>3 itens · 12:21</small></span><b>R$ 174,00</b><em class="status status--paid">Pago</em></div></div></section>
        </section>
      </main>
    </div>`;
}
