export function pedidosView() {
  return `
    <div class="app-shell">
      <aside class="drawer" id="drawer" aria-label="Navegação principal">
        <div class="drawer__top"><a class="brand" href="#inicio" aria-label="AtendeAI início"><img class="brand__logo" src="assets/logo-atendeai.svg" alt="AtendeAI" /></a><button class="icon-button drawer__close" id="close-drawer" type="button" aria-label="Fechar menu"><i data-lucide="x"></i></button></div>
        <nav class="nav-list"><p class="nav-list__label">Visão geral</p><a class="nav-item" href="#inicio"><i data-lucide="layout-dashboard"></i><span>Dashboard</span></a><a class="nav-item is-active" href="#pedidos"><i data-lucide="shopping-bag"></i><span>Pedidos</span><b>12</b></a><a class="nav-item" href="#reservas"><i data-lucide="calendar-days"></i><span>Reservas</span></a><p class="nav-list__label nav-list__label--spaced">Operação</p><a class="nav-item" href="#cardapio"><i data-lucide="utensils"></i><span>Cardápio</span></a><a class="nav-item" href="#clientes"><i data-lucide="users"></i><span>Clientes</span></a><a class="nav-item" href="#relatorios"><i data-lucide="chart-no-axes-combined"></i><span>Relatórios</span></a></nav>
        <div class="drawer__bottom"><a class="nav-item" href="#configuracoes"><i data-lucide="settings-2"></i><span>Configurações</span></a><div class="help-card"><span class="help-card__icon"><i data-lucide="message-circle"></i></span><strong>Precisa de ajuda?</strong><small>Fale com nosso suporte</small><i class="help-card__arrow" data-lucide="arrow-up-right"></i></div><div class="profile"><span class="avatar avatar--orange">JS</span><span><strong>João Silva</strong><small>Administrador</small></span><i data-lucide="more-horizontal"></i></div></div>
      </aside>
      <div class="drawer-overlay" id="drawer-overlay"></div>
      <main class="main-content" id="pedidos">
        <header class="topbar"><button class="icon-button menu-trigger" id="open-drawer" type="button" aria-label="Abrir menu" aria-controls="drawer" aria-expanded="false"><i data-lucide="menu"></i></button><div class="breadcrumb"><span>Operação</span><i data-lucide="chevron-right"></i><strong>Pedidos</strong></div><div class="topbar__actions"><button class="date-picker" type="button"><i data-lucide="calendar"></i> 07 Jun, 2024 <i data-lucide="chevron-down"></i></button><button class="icon-button notification" type="button" aria-label="Notificações"><i data-lucide="bell"></i><span></span></button></div></header>
        <section class="content-wrap orders-page">
          <div class="orders-page__intro"><div><p class="eyebrow">Operação do restaurante</p><h1>Pedidos</h1><p class="subtitle">Acompanhe cada pedido do salão, delivery e retirada em um só lugar.</p></div><div class="orders-page__actions"><span class="live-indicator"><i></i> Operação ao vivo</span><button class="menu-action" id="new-order-button" type="button"><i data-lucide="plus"></i> Novo pedido</button></div></div>
          <div class="order-summary"><article class="summary-card summary-card--active"><span class="summary-card__icon"><i data-lucide="loader-circle"></i></span><span><small>Em andamento</small><strong>12</strong></span><b>+4 hoje</b></article><article class="summary-card"><span class="summary-card__icon summary-card__icon--lime"><i data-lucide="check-check"></i></span><span><small>Concluídos hoje</small><strong>36</strong></span><b>75% do total</b></article><article class="summary-card"><span class="summary-card__icon summary-card__icon--blue"><i data-lucide="clock-3"></i></span><span><small>Tempo médio</small><strong>18 min</strong></span><b>Dentro da meta</b></article></div>
          <section class="panel orders-table-panel"><div class="orders-toolbar"><div class="search-box"><i data-lucide="search"></i><input type="search" placeholder="Buscar pedido, mesa ou cliente" aria-label="Buscar pedido, mesa ou cliente" /></div><div class="orders-filters"><button class="filter-button is-selected" type="button">Todos <b>48</b></button><button class="filter-button" type="button">Em andamento <b>12</b></button><button class="filter-button" type="button">Concluídos</button><button class="filter-button filter-button--icon" type="button" aria-label="Mais filtros"><i data-lucide="sliders-horizontal"></i></button></div></div><div class="orders-table__head"><span>Pedido</span><span>Canal</span><span>Itens</span><span>Horário</span><span>Valor</span><span>Status</span></div><div class="orders-table"><div class="table-order"><span class="table-order__id"><span class="order-icon order-icon--orange"><i data-lucide="shopping-bag"></i></span><strong>#1048</strong><small>Mesa 06 · João Costa</small></span><span class="channel-label"><i data-lucide="utensils"></i> Salão</span><span>2 itens</span><span>12:42</span><strong>R$ 128,00</strong><em class="status status--preparing">Preparando</em></div><div class="table-order"><span class="table-order__id"><span class="order-icon order-icon--green"><i data-lucide="shopping-bag"></i></span><strong>#1047</strong><small>Delivery · Ana Lima</small></span><span class="channel-label"><i data-lucide="bike"></i> Delivery</span><span>4 itens</span><span>12:35</span><strong>R$ 86,50</strong><em class="status status--ready">Pronto</em></div><div class="table-order"><span class="table-order__id"><span class="order-icon order-icon--blue"><i data-lucide="shopping-bag"></i></span><strong>#1046</strong><small>Mesa 12 · Pedro Alves</small></span><span class="channel-label"><i data-lucide="utensils"></i> Salão</span><span>3 itens</span><span>12:21</span><strong>R$ 174,00</strong><em class="status status--paid">Pago</em></div><div class="table-order"><span class="table-order__id"><span class="order-icon order-icon--green"><i data-lucide="shopping-bag"></i></span><strong>#1045</strong><small>Retirada · Carla Souza</small></span><span class="channel-label"><i data-lucide="package-check"></i> Retirada</span><span>1 item</span><span>12:08</span><strong>R$ 42,00</strong><em class="status status--ready">Pronto</em></div></div></section>
        </section>
      </main>
    </div>`;
}
