export function relatoriosView() {
  return `
    <div class="app-shell">
      <aside class="drawer" id="drawer" aria-label="Navegação principal">
        <div class="drawer__top"><a class="brand" href="#inicio" aria-label="AtendeAI início"><img class="brand__logo" src="assets/logo-atendeai.svg" alt="AtendeAI" /></a><button class="icon-button drawer__close" id="close-drawer" type="button" aria-label="Fechar menu"><i data-lucide="x"></i></button></div>
        <nav class="nav-list"><p class="nav-list__label">Visão geral</p><a class="nav-item" href="#inicio"><i data-lucide="layout-dashboard"></i><span>Dashboard</span></a><a class="nav-item" href="#pedidos"><i data-lucide="shopping-bag"></i><span>Pedidos</span><b>12</b></a><a class="nav-item" href="#reservas"><i data-lucide="calendar-days"></i><span>Reservas</span></a><p class="nav-list__label nav-list__label--spaced">Operação</p><a class="nav-item" href="#cardapio"><i data-lucide="utensils"></i><span>Cardápio</span></a><a class="nav-item" href="#clientes"><i data-lucide="users"></i><span>Clientes</span></a><a class="nav-item is-active" href="#relatorios"><i data-lucide="chart-no-axes-combined"></i><span>Relatórios</span></a></nav>
        <div class="drawer__bottom"><a class="nav-item" href="#configuracoes"><i data-lucide="settings-2"></i><span>Configurações</span></a><div class="help-card"><span class="help-card__icon"><i data-lucide="message-circle"></i></span><strong>Precisa de ajuda?</strong><small>Fale com nosso suporte</small><i class="help-card__arrow" data-lucide="arrow-up-right"></i></div><div class="profile"><span class="avatar avatar--orange">JS</span><span><strong>João Silva</strong><small>Administrador</small></span><i data-lucide="more-horizontal"></i></div></div>
      </aside>
      <div class="drawer-overlay" id="drawer-overlay"></div>
      <main class="main-content" id="relatorios">
        <header class="topbar"><button class="icon-button menu-trigger" id="open-drawer" type="button" aria-label="Abrir menu" aria-controls="drawer" aria-expanded="false"><i data-lucide="menu"></i></button><div class="breadcrumb"><span>Visão geral</span><i data-lucide="chevron-right"></i><strong>Relatórios</strong></div><div class="topbar__actions"><button class="date-picker" type="button"><i data-lucide="calendar"></i> 01 - 07 Jun, 2024 <i data-lucide="chevron-down"></i></button><button class="icon-button notification" type="button" aria-label="Notificações"><i data-lucide="bell"></i><span></span></button></div></header>
        <section class="content-wrap reports-page">
          <div class="reports-intro"><div><p class="eyebrow">Inteligência da operação</p><h1>Relatórios</h1><p class="subtitle">Entenda o desempenho do Manjericão e tome decisões melhores.</p></div><button class="export-button" type="button"><i data-lucide="download"></i> Exportar relatório</button></div>
          <div class="report-filters"><button class="report-filter is-selected" data-report-filter="period" type="button">Esta semana <i data-lucide="chevron-down"></i></button><button class="report-filter" data-report-filter="channel" type="button">Todos os canais <i data-lucide="chevron-down"></i></button><span class="report-updated"><i data-lucide="refresh-cw"></i> Atualizado agora</span></div>
          <div class="report-metrics"><article class="report-metric"><span class="report-metric__icon report-metric__icon--orange"><i data-lucide="wallet-cards"></i></span><small>Receita total</small><strong>R$ 12.840,00</strong><span class="report-trend report-trend--up"><i data-lucide="trending-up"></i> 18,4% <em>vs. período anterior</em></span></article><article class="report-metric"><span class="report-metric__icon report-metric__icon--lime"><i data-lucide="shopping-bag"></i></span><small>Total de pedidos</small><strong>284</strong><span class="report-trend report-trend--up"><i data-lucide="trending-up"></i> 12,6% <em>vs. período anterior</em></span></article><article class="report-metric"><span class="report-metric__icon report-metric__icon--blue"><i data-lucide="receipt-text"></i></span><small>Ticket médio</small><strong>R$ 45,21</strong><span class="report-trend report-trend--down"><i data-lucide="trending-down"></i> 3,2% <em>vs. período anterior</em></span></article><article class="report-metric"><span class="report-metric__icon report-metric__icon--pink"><i data-lucide="users"></i></span><small>Clientes atendidos</small><strong>192</strong><span class="report-trend report-trend--up"><i data-lucide="trending-up"></i> 8,9% <em>vs. período anterior</em></span></article></div>
          <div class="reports-grid"><section class="panel report-chart-panel"><div class="panel__header"><div><h2>Receita por dia</h2><p>Comparativo de vendas no período selecionado</p></div><span class="chart-legend"><i></i> Receita</span></div><div class="report-bar-chart"><div class="report-bar-labels"><span>4k</span><span>3k</span><span>2k</span><span>1k</span><span>0</span></div><div class="report-bars"><i style="--value: 48%"><b>Dom</b></i><i style="--value: 67%"><b>Seg</b></i><i style="--value: 54%"><b>Ter</b></i><i style="--value: 75%"><b>Qua</b></i><i style="--value: 62%"><b>Qui</b></i><i style="--value: 88%"><b>Sex</b></i><i class="is-today" style="--value: 96%"><b>Sáb</b></i></div></div></section><section class="panel channel-report"><div class="panel__header"><div><h2>Vendas por canal</h2><p>De onde vêm seus pedidos</p></div></div><div class="channel-report__body"><div class="report-donut"><span>284<small> pedidos</small></span></div><div class="channel-report__legend"><span><i class="channel-dot channel-dot--orange"></i><b>Salão</b><strong>55%</strong></span><span><i class="channel-dot channel-dot--green"></i><b>Delivery</b><strong>32%</strong></span><span><i class="channel-dot channel-dot--blue"></i><b>Retirada</b><strong>13%</strong></span></div></div></section></div>
          <section class="panel dishes-report"><div class="panel__header"><div><h2>Pratos mais vendidos</h2><p>Os favoritos dos seus clientes nesta semana</p></div><a class="text-link" href="#cardapio">Ver cardápio <i data-lucide="arrow-up-right"></i></a></div><div class="dish-ranking"><div class="dish-rank"><span>01</span><span class="dish-rank__icon dish-rank__icon--red">PF</span><strong>Parmegiana da casa</strong><div class="dish-progress"><i style="--value: 92%"></i></div><b>84 pedidos</b></div><div class="dish-rank"><span>02</span><span class="dish-rank__icon dish-rank__icon--green">RS</span><strong>Risoto de cogumelos</strong><div class="dish-progress"><i style="--value: 74%"></i></div><b>67 pedidos</b></div><div class="dish-rank"><span>03</span><span class="dish-rank__icon dish-rank__icon--yellow">BP</span><strong>Bruschetta pomodoro</strong><div class="dish-progress"><i style="--value: 58%"></i></div><b>52 pedidos</b></div></div></section>
        </section>
      </main>
    </div>`;
}
